INSERT INTO tb_number (number) VALUES ('95146');
INSERT INTO tb_number (number) VALUES ('88251');
INSERT INTO tb_number (number) VALUES ('57941');
INSERT INTO tb_number (number) VALUES ('80966');
INSERT INTO tb_number (number) VALUES ('90068');
INSERT INTO tb_number (number) VALUES ('82699');
INSERT INTO tb_number (number) VALUES ('80722');
INSERT INTO tb_number (number) VALUES ('27553');
INSERT INTO tb_number (number) VALUES ('64509');
INSERT INTO tb_number (number) VALUES ('77833');
INSERT INTO tb_number (number) VALUES ('28155');
INSERT INTO tb_number (number) VALUES ('81946');
INSERT INTO tb_number (number) VALUES ('18828');
INSERT INTO tb_number (number) VALUES ('37431');
INSERT INTO tb_number (number) VALUES ('76307');
INSERT INTO tb_number (number) VALUES ('23489');
INSERT INTO tb_number (number) VALUES ('47843');
INSERT INTO tb_number (number) VALUES ('66487');
INSERT INTO tb_number (number) VALUES ('98606');
INSERT INTO tb_number (number) VALUES ('22170');
INSERT INTO tb_number (number) VALUES ('41280');
INSERT INTO tb_number (number) VALUES ('16426');
INSERT INTO tb_number (number) VALUES ('22512');
INSERT INTO tb_number (number) VALUES ('33391');
INSERT INTO tb_number (number) VALUES ('60941');
INSERT INTO tb_number (number) VALUES ('31537');
INSERT INTO tb_number (number) VALUES ('18984');
INSERT INTO tb_number (number) VALUES ('06264');
INSERT INTO tb_number (number) VALUES ('42050');
INSERT INTO tb_number (number) VALUES ('35717');
INSERT INTO tb_number (number) VALUES ('39319');
INSERT INTO tb_number (number) VALUES ('96618');
INSERT INTO tb_number (number) VALUES ('77420');
INSERT INTO tb_number (number) VALUES ('46064');
INSERT INTO tb_number (number) VALUES ('07819');
INSERT INTO tb_number (number) VALUES ('59932');
INSERT INTO tb_number (number) VALUES ('64880');
INSERT INTO tb_number (number) VALUES ('95946');
INSERT INTO tb_number (number) VALUES ('15173');
INSERT INTO tb_number (number) VALUES ('21323');
INSERT INTO tb_number (number) VALUES ('74132');
INSERT INTO tb_number (number) VALUES ('36313');
INSERT INTO tb_number (number) VALUES ('34827');
INSERT INTO tb_number (number) VALUES ('31992');
INSERT INTO tb_number (number) VALUES ('36277');
INSERT INTO tb_number (number) VALUES ('29412');
INSERT INTO tb_number (number) VALUES ('74103');
INSERT INTO tb_number (number) VALUES ('27441');
INSERT INTO tb_number (number) VALUES ('87466');
INSERT INTO tb_number (number) VALUES ('26157');

INSERT INTO tb_player (email) VALUES ('diam@vulputate.com');
INSERT INTO tb_player (email) VALUES ('amet.risus@infaucibusorci.net');
INSERT INTO tb_player (email) VALUES ('sit@eget.ca');
INSERT INTO tb_player (email) VALUES ('Sed.congue@dolor.edu');
INSERT INTO tb_player (email) VALUES ('Donec.sollicitudin.adipiscing@Nulla.co.uk');
INSERT INTO tb_player (email) VALUES ('risus@noncursusnon.edu');
INSERT INTO tb_player (email) VALUES ('ut.sem.Nulla@ante.ca');
INSERT INTO tb_player (email) VALUES ('a.nunc@arcuMorbisit.co.uk');
INSERT INTO tb_player (email) VALUES ('sollicitudin@enimdiamvel.ca');
INSERT INTO tb_player (email) VALUES ('ipsum@fringilla.net');
INSERT INTO tb_player (email) VALUES ('mauris.sagittis.placerat@egetmetuseu.co.uk');
INSERT INTO tb_player (email) VALUES ('mollis@aliquet.co.uk');
INSERT INTO tb_player (email) VALUES ('non.lobortis@mus.net');
INSERT INTO tb_player (email) VALUES ('Quisque@dolorNulla.org');
INSERT INTO tb_player (email) VALUES ('tellus.imperdiet.non@pharetraNamac.ca');
INSERT INTO tb_player (email) VALUES ('parturient@natoquepenatibus.edu');
INSERT INTO tb_player (email) VALUES ('eget.metus@et.org');
INSERT INTO tb_player (email) VALUES ('interdum.Curabitur.dictum@montes.net');
INSERT INTO tb_player (email) VALUES ('augue@blandit.com');
INSERT INTO tb_player (email) VALUES ('cursus.et.eros@facilisiSedneque.edu');
INSERT INTO tb_player (email) VALUES ('Aliquam@mattisInteger.co.uk');
INSERT INTO tb_player (email) VALUES ('Morbi.accumsan.laoreet@Proin.ca');
INSERT INTO tb_player (email) VALUES ('faucibus.orci.luctus@dapibusquam.net');
INSERT INTO tb_player (email) VALUES ('enim.Mauris@sociisnatoquepenatibus.co.uk');
INSERT INTO tb_player (email) VALUES ('Sed.malesuada@Fusce.co.uk');
INSERT INTO tb_player (email) VALUES ('ante@risusDonec.ca');
INSERT INTO tb_player (email) VALUES ('In@sed.net');
INSERT INTO tb_player (email) VALUES ('sagittis.augue@vitaerisusDuis.edu');
INSERT INTO tb_player (email) VALUES ('ligula.eu.enim@fringillacursus.co.uk');
INSERT INTO tb_player (email) VALUES ('et.magnis.dis@tinciduntadipiscing.ca');
INSERT INTO tb_player (email) VALUES ('Phasellus@blandit.org');
INSERT INTO tb_player (email) VALUES ('porta@et.org');
INSERT INTO tb_player (email) VALUES ('aliquet.vel.vulputate@indolorFusce.com');
INSERT INTO tb_player (email) VALUES ('turpis@elitafeugiat.net');
INSERT INTO tb_player (email) VALUES ('vel.arcu@tincidunt.net');
INSERT INTO tb_player (email) VALUES ('Sed@gravidasitamet.com');
INSERT INTO tb_player (email) VALUES ('ultrices.Duis@musAeneaneget.com');
INSERT INTO tb_player (email) VALUES ('habitant@Proinvelnisl.com');
INSERT INTO tb_player (email) VALUES ('mi.tempor.lorem@velquam.ca');
INSERT INTO tb_player (email) VALUES ('massa@id.com');
INSERT INTO tb_player (email) VALUES ('libero@senectusetnetus.ca');
INSERT INTO tb_player (email) VALUES ('hymenaeos@Sedegetlacus.net');
INSERT INTO tb_player (email) VALUES ('nunc.Quisque.ornare@Nam.edu');
INSERT INTO tb_player (email) VALUES ('In.at@lacus.org');
INSERT INTO tb_player (email) VALUES ('et.malesuada.fames@pellentesqueeget.ca');
INSERT INTO tb_player (email) VALUES ('eget.magna@euismod.co.uk');
INSERT INTO tb_player (email) VALUES ('nec@feugiat.ca');
INSERT INTO tb_player (email) VALUES ('velit.Cras@sodalesat.ca');
INSERT INTO tb_player (email) VALUES ('dui@Maurismolestiepharetra.edu');
INSERT INTO tb_player (email) VALUES ('diam@laoreetposuereenim.ca');

INSERT INTO tb_player_number (player_id, number_id) VALUES (1 , 7);
INSERT INTO tb_player_number (player_id, number_id) VALUES (1 , 11);
INSERT INTO tb_player_number (player_id, number_id) VALUES (1 , 2);
INSERT INTO tb_player_number (player_id, number_id) VALUES (1 , 5);
INSERT INTO tb_player_number (player_id, number_id) VALUES (1 , 8);
INSERT INTO tb_player_number (player_id, number_id) VALUES (2 , 3);
INSERT INTO tb_player_number (player_id, number_id) VALUES (2 , 15);
INSERT INTO tb_player_number (player_id, number_id) VALUES (2 , 9);
INSERT INTO tb_player_number (player_id, number_id) VALUES (2 , 10);
INSERT INTO tb_player_number (player_id, number_id) VALUES (5 , 27);
INSERT INTO tb_player_number (player_id, number_id) VALUES (5 , 14);
INSERT INTO tb_player_number (player_id, number_id) VALUES (7 , 17);
INSERT INTO tb_player_number (player_id, number_id) VALUES (7 , 22);
INSERT INTO tb_player_number (player_id, number_id) VALUES (3 , 33);
INSERT INTO tb_player_number (player_id, number_id) VALUES (3 , 44);